"""ItemHistory name col

Revision ID: 637c34073de2
Revises: b09481414bf3
Create Date: 2021-01-23 18:20:42.891607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637c34073de2'
down_revision = 'b09481414bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_history', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_item_history_name'), 'item_history', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_history_name'), table_name='item_history')
    op.drop_column('item_history', 'name')
    # ### end Alembic commands ###
