"""ItemHistory barcode fix

Revision ID: c9ede0d7fab8
Revises: b24fcd4cb13e
Create Date: 2021-01-23 18:26:00.007036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ede0d7fab8'
down_revision = 'b24fcd4cb13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_history_barcode', table_name='item_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_item_history_barcode', 'item_history', ['barcode'], unique=1)
    # ### end Alembic commands ###
